BlockstreamResearch/SimplicityHL

- Cargo.lock
- Cargo.toml
- example_progs/add.simpl
- example_progs/assertr.simpl
- example_progs/cat.simpl
- example_progs/match.simpl
- example_progs/test.simpl
- src/compile.rs
- src/lib.rs
- src/minimal.pest
- src/parse.rs
- src/scope.rs
Implementation of new syntax and semantics from #6: types, values, match statements, unwraps.
The Simplicity compiler panics on every error, as on master. I will fix this in a follow-up PR.
Types and patterns are parsed nonrecursively. Expressions are more complicated and are currently parsed recursively. There will be a follow-up PR.
> New grammar

- Cargo.toml
- example_progs/array.simpl
- src/array.rs
- src/minimal.pest
- src/parse.rs
- src/scope.rs
Enable destructing of arrays in let statements `let [a, b,c] = (1, 2, 3)`, using array patterns. Do some refactors beforehand.
> Array patterns

- Cargo.lock
- Cargo.toml
Use the latest rust-simplicity master which is compatible with WASM. The version on crates.io is not yet compatible.
Depends on https://github.com/BlockstreamResearch/rust-simplicity/pull/214
> Make WASM compatible

- src/compile.rs
- src/lib.rs
- src/named.rs
- src/scope.rs
Mostly, moves `unwrap`s out of hiding into the compiler where they belong. I did not vet that any of the remaining unwrap()s are actually correct. But I was able to eliminate a ton of them that I was sure *were* correct.
> Some error improvements

- src/array.rs
- src/error.rs
- src/lib.rs
- src/main.rs
- src/parse.rs
Add infrastructure for relaying pretty errors to the user. Enable errors during parsing (the compiler still panics). Avoid unwraps.
Format the error messages similar to how the rust compiler does it.
```
|
1 | let a1: List<u32, 2> = None;
|              ^^^^^^ List bound must be a power of two greater one: 2, 4, 8, 16, 32, ...
```
Support multi-line errors.
```
|
2 | let x: u32 = Left(
3 |     Right(0)
4 | );
| ^^^^^^^^^^^^^^^^^^ Type mismatch: Expected value of type `u32`, got `Either<Either<_, u32>, _>`
```
An error (`RichError`) consists of an error variant (`Error`) and a context (spanned area inside a file). During parsing we attach the line/column position of the affected area. The parser works on local chunks and doesn't have access to the entire file. When parsing is done, we …
> Parse with errors

- src/compile.rs
- src/error.rs
- src/lib.rs
- src/parse.rs
- src/scope.rs
Extend #34 to include compile errors.
> Compile with errors

- src/compile.rs
- src/named.rs
Introduce infallible assertions and use them in the compiler.
It turns out, assertions _can_ fail if the source type of the child is a unit or sum type. No upstream fix is needed.
> Infallible assertions

- Cargo.lock
- Cargo.toml
- src/array.rs
- src/compile.rs
- src/lib.rs
- src/named.rs
- src/parse.rs
- src/scope.rs
Generalize the scope to return values of multiple variables inside a pattern. We will use these values as function call arguments. The seeked value is returned by a Simplicity expression that is compressed.
Add supporting structs and documentation.
Supersedes #23
> Generalize Scope

- Cargo.lock
- Cargo.toml
- src/compile.rs
- src/error.rs
- src/lib.rs
- src/parse.rs
- src/types.rs
Move types into their separate module. Rename `Type` to `ResolvedType` to better reflect its function in face of future aliased types. Introduce `StructuralType` to represent Simplicity types in the code base. Implement `From` and `TryFrom` to inter-type conversions. Introduce `TypeInner` to handle type primitives of both resolved and future aliased types.
> Type module

- src/error.rs
- src/lib.rs
- src/parse.rs
- src/value.rs
Add representation of values in correspondence to the newly added type module:
- `UIntValue` ↔ `UIntType`
- `Value` ↔ `ResolvedType`
- `StructuralValue` ↔ `StructuralType`
- `ValueConstructible` ↔ `TypeConstructible`
Depends on #47
> Add values

- src/types.rs
- src/value.rs
Add tuple types and values. We need tuples to represent function arguments, which have heterogeneous types. Up to this point, we abused arrays for this purpose, because tuple and arrays have the same Simplicity structure. When we give Simfony proper types, this hack will no longer work.
Tuples subsume unit and product: Unit is the empty tuple and a product is a 2-tuple. For now, keep the grammar as before, which means only 0-tuples and 2-tuples are allowed.
Depends on #49
> Add tuples

- example_progs/tuple.simf
- src/compile.rs
- src/lib.rs
- src/minimal.pest
- src/parse.rs
- src/scope.rs
Depends on #51 
Make tuple values constructible in the Simfony grammar. Remove units and products as they are subsumed by tuples (0-tuples and 2-tuples, respectively). Add tuple patterns.
> Tuple values

- src/compile.rs
- src/named.rs
- src/pattern.rs
Simfony expressions are translated into Simplicity expressions with a variable source type. This means that pairs can be constructed infallibly. Use `PairBuilder` to ensure this invariant at compile time and remove unnecessary unwraps.
> Infallible pairs

- Cargo.toml
- src/lib.rs
- src/minimal.pest
- src/parse.rs
I set up the fuzzing infrastructure as described in #72 and looked for crashes. I fixed the bug that Andrew found in #72. There were no more crashes, but it turns out that parsing can be really show when opening `(`, `[`, `{` are spammed and not closed. This seems to be an issue with the PEST parser itself. I will look into fixing this, but for now I will just note that parsing can be slow. Unfortunately, this also means that fuzzing is slow. I found no way to skip slow units during fuzzing. I limited the input size to around 50 bytes, but even this produces slow units.
> Fuzz fixes

- src/named.rs
- src/pattern.rs
Depends on #80 _(because of the inference context parameters)_
Fixes #39 Fixes #40
> Fix asymptotics of BasePattern

- Cargo.lock
- Cargo.toml
- fuzz/Cargo.toml
- fuzz/fuzz_targets/reconstruct_value.rs
- src/array.rs
- src/ast.rs
- src/compile.rs
- src/lib.rs
- src/parse.rs
- src/types.rs
- src/value.rs
- src/witness.rs
Convert Simplicity values back to Simfony values via a Simfony type. We need this to display debug output from the Simplicity Bit Machine in terms of Simfony speak. Fix bugs that came up during fuzzing.
> Reconstruct value

- .github/workflows/test.yml
- fuzz/Cargo.toml
- fuzz/fuzz_targets/parse_value_rtt.rs
- fuzz/fuzz_targets/parse_witness_json_rtt.rs
- fuzz/fuzz_targets/parse_witness_module_rtt.rs
- fuzz/fuzz_targets/reconstruct_value.rs
- justfile
- src/ast.rs
- src/error.rs
- src/minimal.pest
- src/parse.rs
- src/str.rs
- src/witness.rs
Make witness JSON parsing via serde optional. Introduce witness modules as an alternative way to provide witness data. Witness modules are written directly inside the Simfony source code.
> Add witness module

- bitcoind-tests/tests/common/daemon.rs
- bitcoind-tests/tests/common/test.rs
- bitcoind-tests/tests/spend_utxo.rs
- examples/p2pk.args
- examples/p2pk.simf
- examples/p2pk.wit
- fuzz/fuzz_targets/compile_parse_tree.rs
- fuzz/fuzz_targets/compile_text.rs
- src/ast.rs
- src/compile.rs
- src/error.rs
- src/lib.rs
- src/main.rs
- src/minimal.pest
- src/named.rs
- src/parse.rs
- src/serde.rs
- src/str.rs
- src/value.rs
- src/witness.rs
Refactor the code that handles witness types / values / modules. Add parameterized values to Simfony which are instantiated at commitment time.
Simfony programs with parameters are templates for a family of Simfony programs. A template is instantiated by providing arguments to its parameters. Arguments can be provided via JSON or via code `mod param { ... }`.
The existing API needed to be updated to handle parameters. This turned out to be more work than expected :) While most changes are mechanical, there were some interesting engineering problems, such as handling parameters inside fuzz tests.
> Parameterize programs

- src/value.rs
- src/witness.rs
Fixes how modules and values are displayed.
> Fix display

- src/lib.rs
- src/minimal.pest
- src/parse.rs
Type aliases didn't parse as expected. This PR fixes that.
> Fix type alias

- .github/workflows/book.yml
- src/ast.rs
- src/error.rs
- src/minimal.pest
- src/parse.rs
- src/str.rs
- src/types.rs
> Fix sampling

- examples/non_interactive_fee_bump.simf
- examples/non_interactive_fee_bump.wit
- src/array.rs
- src/ast.rs
- src/dummy_env.rs
- src/error.rs
- src/lib.rs
- src/parse.rs
- src/pattern.rs
- src/types.rs
- src/value.rs
Had to refactor some of the dummy_env stuff.
If I try to include change output in the default env, everything breaks and I did not want to spend time trying to fix all of tests. Instead, we create a new default with fee just for this one test case.
> Add Non interactive fee bumping example

- .gitignore
- README.md
- vscode/LICENSE
- vscode/README.md
- vscode/language-configuration.json
- vscode/package-lock.json
- vscode/package.json
- vscode/syntaxes/simfony.tmLanguage.json
This PR adds a minimal extension for VSCode that highlights *.simf files and also enables basic things like auto commenting/uncommenting (when you press cmd+/).
> Add VSCode extension with syntax highlighter

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
Move from git deps to crates.io deps, add CHANGELOG.md. From here on out I'd like us to have a somewhat regular release cadence even if we're aware of major issues.
Fixes #121.
> prepare for initial release

- src/lib.rs
This PR exposes an API for satisfying a program with pruning given an optional environment.  
The naming might be a bit misleading (maybe `satisfy_pruned` would be better?), pls let me know if you want to change.
> Satisfy program with optional pruning

- Cargo.lock
- Cargo.toml
- src/main.rs
Add clap as a dependency and use it to parse the command line arguments. Also add a --debug cli option to include debug symbols.
> Use clap for parsing CLI args

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- clippy.toml
- src/lib.rs
- src/main.rs
No major changes (well, many changes since simfony 0.1 in April); but we are ready to release under the new name.
> Update rust-simplicity dep and prepare for initial release

- book/src/SUMMARY.md
While I'd love to know what was going to be added here, it's better that we remove the headline until we have content for it.
> remove orphan heading "Locking and unlocking UTXOs"

- README.md
- book/src/function.md
- book/src/let_statement.md
- book/src/type.md
- book/src/type_casting.md
- doc/environment.md
- doc/translation.md
Ok I have simplified my pull request. 
Thanks
> Minor Clean Up
